INSERT INTO jatekosok(id, club, name, position, number) VALUES (1, 'Arsenal', 'Bernd Leno', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (2, 'Arsenal', 'Arthur Okonkwo', 'Goalkeeper', 33);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (3, 'Arsenal', 'Karl Hein', 'Goalkeeper', 49);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (4, 'Arsenal', 'Aaron Ramsdale', 'Goalkeeper', 32);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (5, 'Arsenal', 'Kieran Tierney', 'Defender', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (6, 'Arsenal', 'Gabriel Magalhães', 'Defender', 6);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (7, 'Arsenal', 'Rob Holding', 'Defender', 16);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (8, 'Arsenal', 'Cédric Soares', 'Defender', 17);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (9, 'Arsenal', 'Calum Chambers', 'Defender', 21);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (10, 'Arsenal', 'Pablo Marí', 'Defender', 22);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (11, 'Arsenal', 'Sead Kolasinac', 'Defender', 31);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (12, 'Arsenal', 'Nuno Tavares', 'Defender', 20);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (13, 'Arsenal', 'Benjamin White', 'Defender', 4);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (14, 'Arsenal', 'Takehiro Tomiyasu', 'Defender', 18);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (15, 'Arsenal', 'Bukayo Saka', 'Midfielder', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (16, 'Arsenal', 'Thomas Partey', 'Midfielder', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (17, 'Arsenal', 'Mohamed Elneny', 'Midfielder', 25);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (18, 'Arsenal', 'Emile Smith Rowe', 'Midfielder', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (19, 'Arsenal', 'Granit Xhaka', 'Midfielder', 34);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (20, 'Arsenal', 'Ainsley Maitland-Niles', 'Midfielder', 15);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (21, 'Arsenal', 'Albert Sambi Lokonga', 'Midfielder', 23);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (22, 'Arsenal', 'Martin Ødegaard', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (23, 'Arsenal', 'Salah-Eddine Oulad M"hand', 'Midfielder', 65);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (24, 'Arsenal', 'Alexandre Lacazette', 'Forward', 9);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (25, 'Arsenal', 'Pierre-Emerick Aubameyang', 'Forward', 14);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (26, 'Arsenal', 'Nicolas Pépé', 'Forward', 19);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (27, 'Arsenal', 'Eddie Nketiah', 'Forward', 30);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (28, 'Arsenal', 'Gabriel Martinelli', 'Forward', 35);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (29, 'Arsenal', 'Folarin Balogun', 'Forward', 26);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (30, 'Aston Villa', 'Jed Steer', 'Goalkeeper', 12);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (31, 'Aston Villa', 'Emiliano Martínez', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (32, 'Aston Villa', 'Viljami Sinisalo', 'Goalkeeper', 38);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (33, 'Aston Villa', 'Matthew Cash', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (34, 'Aston Villa', 'Ezri Konsa', 'Defender', 4);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (35, 'Aston Villa', 'Tyrone Mings', 'Defender', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (36, 'Aston Villa', 'Matt Targett', 'Defender', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (37, 'Aston Villa', 'Kortney Hause', 'Defender', 30);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (38, 'Aston Villa', 'Ashley Young', 'Defender', 18);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (39, 'Aston Villa', 'Axel Tuanzebe', 'Defender', 16);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (40, 'Aston Villa', 'Sil Swinkels', 'Defender', 50);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (41, 'Aston Villa', 'Douglas Luiz', 'Midfielder', 6);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (42, 'Aston Villa', 'John McGinn', 'Midfielder', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (43, 'Aston Villa', 'Trézéguet', 'Midfielder', 17);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (44, 'Aston Villa', 'Marvelous Nakamba', 'Midfielder', 19);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (45, 'Aston Villa', 'Anwar El Ghazi', 'Midfielder', 21);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (46, 'Aston Villa', 'Morgan Sanson', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (47, 'Aston Villa', 'Jacob Ramsey', 'Midfielder', 41);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (48, 'Aston Villa', 'Emiliano Buendía', 'Midfielder', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (49, 'Aston Villa', 'Jaden Philogene-Bidace', 'Midfielder', 32);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (50, 'Aston Villa', 'Carney Chukwuemeka', 'Midfielder', 33);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (51, 'Aston Villa', 'Aaron Ramsey', 'Midfielder', 40);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (52, 'Aston Villa', 'Lamare Bogarde', 'Midfielder', 36);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (53, 'Aston Villa', 'Hayden Lindley', 'Midfielder', 49);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (54, 'Aston Villa', 'Ollie Watkins', 'Forward', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (55, 'Aston Villa', 'Bertrand Traoré', 'Forward', 15);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (56, 'Aston Villa', 'Keinan Davis', 'Forward', 39);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (57, 'Aston Villa', 'Leon Bailey', 'Forward', 31);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (58, 'Aston Villa', 'Danny Ings', 'Forward', 20);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (59, 'Aston Villa', 'Caleb Chukwuemeka', 'Forward', 46);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (60, 'Aston Villa', 'Cameron Archer', 'Forward', 35);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (61, 'Brentford', 'David Raya', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (62, 'Brentford', 'Álvaro Fernández', 'Goalkeeper', 40);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (63, 'Brentford', 'Matthew Cox', 'Goalkeeper', 41);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (64, 'Brentford', 'Rico Henry', 'Defender', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (65, 'Brentford', 'Charlie Goode', 'Defender', 4);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (66, 'Brentford', 'Ethan Pinnock', 'Defender', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (67, 'Brentford', 'Pontus Jansson', 'Defender', 18);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (68, 'Brentford', 'Mads Bech Sørensen', 'Defender', 29);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (69, 'Brentford', 'Mads Roerslev', 'Defender', 30);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (70, 'Brentford', 'Dominic Thompson', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (71, 'Brentford', 'Julian Jeanvier', 'Defender', 23);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (72, 'Brentford', 'Luka Racic', 'Defender', 32);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (73, 'Brentford', 'Finley Stevens', 'Defender', 36);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (74, 'Brentford', 'Lewis Gordon', 'Defender', 39);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (75, 'Brentford', 'Kristoffer Ajer', 'Defender', 20);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (76, 'Brentford', 'Zanka', 'Defender', 22);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (77, 'Brentford', 'Daniel Oyegoke', 'Defender', 34);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (78, 'Brentford', 'Christian Nørgaard', 'Midfielder', 6);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (79, 'Brentford', 'Mathias Jensen', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (80, 'Brentford', 'Josh Dasilva', 'Midfielder', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (81, 'Brentford', 'Bryan Mbeumo', 'Midfielder', 19);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (82, 'Brentford', 'Tariqe Fosu-Henry', 'Midfielder', 24);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (83, 'Brentford', 'Shandon Baptiste', 'Midfielder', 26);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (84, 'Brentford', 'Vitaly Janelt', 'Midfielder', 27);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (85, 'Brentford', 'Jan Zamburek', 'Midfielder', 31);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (86, 'Brentford', 'Mads Bidstrup', 'Midfielder', 28);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (87, 'Brentford', 'Maxwell Haygarth', 'Midfielder', 37);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (88, 'Brentford', 'Frank Onyeka', 'Midfielder', 15);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (89, 'Brentford', 'Myles Peart-Harris', 'Midfielder', 25);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (90, 'Brentford', 'Yoane Wissa', 'Midfielder', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (91, 'Brentford', 'Paris Maghoma', 'Midfielder', 33);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (92, 'Brentford', 'Sergi Canós', 'Forward', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (93, 'Brentford', 'Marcus Forss', 'Forward', 9);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (94, 'Brentford', 'Ivan Toney', 'Forward', 17);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (95, 'Brentford', 'Saman Ghoddos', 'Forward', 14);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (96, 'Brighton and Hove Albion', 'Jason Steele', 'Goalkeeper', 23);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (97, 'Brighton and Hove Albion', 'Robert Sánchez', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (98, 'Brighton and Hove Albion', 'Kjell Scherpen', 'Goalkeeper', 16);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (99, 'Brighton and Hove Albion', 'Thomas McGill', 'Goalkeeper', 38);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (100, 'Brighton and Hove Albion', 'Tariq Lamptey', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (101, 'Brighton and Hove Albion', 'Adam Webster', 'Defender', 4);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (102, 'Brighton and Hove Albion', 'Lewis Dunk', 'Defender', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (103, 'Brighton and Hove Albion', 'Dan Burn', 'Defender', 33);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (104, 'Brighton and Hove Albion', 'Joël Veltman', 'Defender', 34);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (105, 'Brighton and Hove Albion', 'Shane Duffy', 'Defender', 24);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (106, 'Brighton and Hove Albion', 'Haydon Roberts', 'Defender', 28);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (107, 'Brighton and Hove Albion', 'James Furlong', 'Defender', 54);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (108, 'Brighton and Hove Albion', 'Odeluga Offiah', 'Defender', 57);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (109, 'Brighton and Hove Albion', 'Antef Tsoungui', 'Defender', 53);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (110, 'Brighton and Hove Albion', 'Marc Cucurella', 'Defender', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (111, 'Brighton and Hove Albion', 'Tudor Baluta', 'Defender', 35);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (112, 'Brighton and Hove Albion', 'Ed Turns', 'Defender', 55);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (113, 'Brighton and Hove Albion', 'Yves Bissouma', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (114, 'Brighton and Hove Albion', 'Alexis Mac Allister', 'Midfielder', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (115, 'Brighton and Hove Albion', 'Pascal Groß', 'Midfielder', 13);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (116, 'Brighton and Hove Albion', 'Adam Lallana', 'Midfielder', 14);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (117, 'Brighton and Hove Albion', 'Jakub Moder', 'Midfielder', 15);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (118, 'Brighton and Hove Albion', 'Steven Alzate', 'Midfielder', 17);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (119, 'Brighton and Hove Albion', 'Solly March', 'Midfielder', 20);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (120, 'Brighton and Hove Albion', 'Enock Mwepu', 'Midfielder', 12);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (121, 'Brighton and Hove Albion', 'Taylor Richards', 'Midfielder', 30);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (122, 'Brighton and Hove Albion', 'Marc Leonard', 'Midfielder', 42);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (123, 'Brighton and Hove Albion', 'Andrew Moran', 'Midfielder', 59);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (124, 'Brighton and Hove Albion', 'Aaron Connolly', 'Forward', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (125, 'Brighton and Hove Albion', 'Neal Maupay', 'Forward', 9);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (126, 'Brighton and Hove Albion', 'Leandro Trossard', 'Forward', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (127, 'Brighton and Hove Albion', 'Danny Welbeck', 'Forward', 18);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (128, 'Brighton and Hove Albion', 'Evan Ferguson', 'Forward', 58);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (129, 'Brighton and Hove Albion', 'Jürgen Locadia', 'Forward', 27);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (130, 'Brighton and Hove Albion', 'Jeremy Sarmiento', 'Forward', 60);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (131, 'Burnley', 'Nick Pope', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (132, 'Burnley', 'Will Norris', 'Goalkeeper', 25);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (133, 'Burnley', 'Wayne Hennessey', 'Goalkeeper', 13);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (134, 'Burnley', 'Matthew Lowton', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (135, 'Burnley', 'Charlie Taylor', 'Defender', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (136, 'Burnley', 'James Tarkowski', 'Defender', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (137, 'Burnley', 'Ben Mee', 'Defender', 6);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (138, 'Burnley', 'Erik Pieters', 'Defender', 23);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (139, 'Burnley', 'Phil Bardsley', 'Defender', 26);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (140, 'Burnley', 'Kevin Long', 'Defender', 28);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (141, 'Burnley', 'Nathan Collins', 'Defender', 22);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (142, 'Burnley', 'Bobby Thomas', 'Defender', 37);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (143, 'Burnley', 'Owen Dodgson', 'Defender', 39);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (144, 'Burnley', 'Maxwel Cornet', 'Defender', 20);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (145, 'Burnley', 'Connor Roberts', 'Defender', 14);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (146, 'Burnley', 'Jack Cork', 'Midfielder', 4);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (147, 'Burnley', 'Jóhann Gudmundsson', 'Midfielder', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (148, 'Burnley', 'Josh Brownhill', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (149, 'Burnley', 'Dwight McNeil', 'Midfielder', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (150, 'Burnley', 'Dale Stephens', 'Midfielder', 16);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (151, 'Burnley', 'Ashley Westwood', 'Midfielder', 18);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (152, 'Burnley', 'Lewis Richardson', 'Midfielder', 38);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (153, 'Burnley', 'Aaron Lennon', 'Midfielder', 17);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (154, 'Burnley', 'Chris Wood', 'Forward', 9);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (155, 'Burnley', 'Ashley Barnes', 'Forward', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (156, 'Burnley', 'Jay Rodriguez', 'Forward', 19);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (157, 'Burnley', 'Matej Vydra', 'Forward', 27);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (158, 'Chelsea', 'Kepa Arrizabalaga', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (159, 'Chelsea', 'Édouard Mendy', 'Goalkeeper', 16);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (160, 'Chelsea', 'Marcus Bettinelli', 'Goalkeeper', 13);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (161, 'Chelsea', 'Lucas Bergström', 'Goalkeeper', 36);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (162, 'Chelsea', 'Antonio Rüdiger', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (163, 'Chelsea', 'Marcos Alonso', 'Defender', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (164, 'Chelsea', 'Andreas Christensen', 'Defender', 4);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (165, 'Chelsea', 'Thiago Silva', 'Defender', 6);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (166, 'Chelsea', 'Ben Chilwell', 'Defender', 21);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (167, 'Chelsea', 'Reece James', 'Defender', 24);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (168, 'Chelsea', 'César Azpilicueta', 'Defender', 28);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (169, 'Chelsea', 'Trevoh Chalobah', 'Defender', 14);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (170, 'Chelsea', 'Malang Sarr', 'Defender', 31);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (171, 'Chelsea', 'Xavier Mbuyamba', 'Defender', 43);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (172, 'Chelsea', 'Jorginho', 'Midfielder', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (173, 'Chelsea', 'N"Golo Kanté', 'Midfielder', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (174, 'Chelsea', 'Christian Pulisic', 'Midfielder', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (175, 'Chelsea', 'Mateo Kovacic', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (176, 'Chelsea', 'Mason Mount', 'Midfielder', 19);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (177, 'Chelsea', 'Hakim Ziyech', 'Midfielder', 22);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (178, 'Chelsea', 'Kai Havertz', 'Midfielder', 29);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (179, 'Chelsea', 'Ruben Loftus-Cheek', 'Midfielder', 12);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (180, 'Chelsea', 'Saúl Ñíguez', 'Midfielder', 17);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (181, 'Chelsea', 'Ross Barkley', 'Midfielder', 18);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (182, 'Chelsea', 'Timo Werner', 'Forward', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (183, 'Chelsea', 'Callum Hudson-Odoi', 'Forward', 20);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (184, 'Chelsea', 'Romelu Lukaku', 'Forward', 9);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (185, 'Crystal Palace', 'Jack Butland', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (186, 'Crystal Palace', 'Vicente Guaita', 'Goalkeeper', 13);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (187, 'Crystal Palace', 'Remi Matthews', 'Goalkeeper', 19);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (188, 'Crystal Palace', 'Joel Ward', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (189, 'Crystal Palace', 'James Tomkins', 'Defender', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (190, 'Crystal Palace', 'Nathaniel Clyne', 'Defender', 17);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (191, 'Crystal Palace', 'Tyrick Mitchell', 'Defender', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (192, 'Crystal Palace', 'Martin Kelly', 'Defender', 34);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (193, 'Crystal Palace', 'Nathan Ferguson', 'Defender', 36);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (194, 'Crystal Palace', 'Marc Guéhi', 'Defender', 6);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (195, 'Crystal Palace', 'Joachim Andersen', 'Defender', 16);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (196, 'Crystal Palace', 'Reece Hannam', 'Defender', 43);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (197, 'Crystal Palace', 'Luka Milivojevic', 'Midfielder', 4);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (198, 'Crystal Palace', 'Cheikhou Kouyaté', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (199, 'Crystal Palace', 'Jeffrey Schlupp', 'Midfielder', 15);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (200, 'Crystal Palace', 'James McArthur', 'Midfielder', 18);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (201, 'Crystal Palace', 'Eberechi Eze', 'Midfielder', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (202, 'Crystal Palace', 'Jairo Riedewald', 'Midfielder', 44);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (203, 'Crystal Palace', 'Michael Olise', 'Midfielder', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (204, 'Crystal Palace', 'Conor Gallagher', 'Midfielder', 23);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (205, 'Crystal Palace', 'Jesurun Rak-Sakyi', 'Midfielder', 49);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (206, 'Crystal Palace', 'Will Hughes', 'Midfielder', 12);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (207, 'Crystal Palace', 'Jordan Ayew', 'Forward', 9);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (208, 'Crystal Palace', 'Wilfried Zaha', 'Forward', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (209, 'Crystal Palace', 'Jean-Philippe Mateta', 'Forward', 14);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (210, 'Crystal Palace', 'Christian Benteke', 'Forward', 20);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (211, 'Crystal Palace', 'Robert Street', 'Forward', 46);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (212, 'Crystal Palace', 'Scott Banks', 'Forward', 40);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (213, 'Crystal Palace', 'Odsonne Édouard', 'Forward', 22);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (214, 'Everton', 'Jordan Pickford', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (215, 'Everton', 'Asmir Begovic', 'Goalkeeper', 15);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (216, 'Everton', 'Andy Lonergan', 'Goalkeeper', 31);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (217, 'Everton', 'Harry Tyrer', 'Goalkeeper', 53);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (218, 'Everton', 'Mason Holgate', 'Defender', 4);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (219, 'Everton', 'Michael Keane', 'Defender', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (220, 'Everton', 'Lucas Digne', 'Defender', 12);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (221, 'Everton', 'Yerry Mina', 'Defender', 13);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (222, 'Everton', 'Ben Godfrey', 'Defender', 22);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (223, 'Everton', 'Séamus Coleman', 'Defender', 23);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (224, 'Everton', 'Jonjoe Kenny', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (225, 'Everton', 'Jarrad Branthwaite', 'Defender', 32);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (226, 'Everton', 'Reece Welch', 'Defender', 64);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (227, 'Everton', 'Allan', 'Midfielder', 6);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (228, 'Everton', 'Fabian Delph', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (229, 'Everton', 'Gylfi Sigurdsson', 'Midfielder', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (230, 'Everton', 'Abdoulaye Doucouré', 'Midfielder', 16);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (231, 'Everton', 'André Gomes', 'Midfielder', 21);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (232, 'Everton', 'Jean-Philippe Gbamin', 'Midfielder', 25);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (233, 'Everton', 'Tom Davies', 'Midfielder', 26);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (234, 'Everton', 'Andros Townsend', 'Midfielder', 14);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (235, 'Everton', 'Charlie Whitaker', 'Midfielder', 57);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (236, 'Everton', 'Richarlison', 'Forward', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (237, 'Everton', 'Dominic Calvert-Lewin', 'Forward', 9);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (238, 'Everton', 'Alex Iwobi', 'Forward', 17);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (239, 'Everton', 'Cenk Tosun', 'Forward', 20);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (240, 'Everton', 'Demarai Gray', 'Forward', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (241, 'Everton', 'Anthony Gordon', 'Forward', 24);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (242, 'Everton', 'Salomón Rondón', 'Forward', 33);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (243, 'Everton', 'Ellis Simms', 'Forward', 50);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (244, 'Everton', 'Lewis Dobbin', 'Forward', 61);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (245, 'Leeds United', 'Illan Meslier', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (246, 'Leeds United', 'Kristoffer Klaesson', 'Goalkeeper', 13);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (247, 'Leeds United', 'Luke Ayling', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (248, 'Leeds United', 'Robin Koch', 'Defender', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (249, 'Leeds United', 'Liam Cooper', 'Defender', 6);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (250, 'Leeds United', 'Diego Llorente', 'Defender', 14);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (251, 'Leeds United', 'Pascal Struijk', 'Defender', 21);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (252, 'Leeds United', 'Laurens De Bock', 'Defender', 12);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (253, 'Leeds United', 'Junior Firpo', 'Defender', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (254, 'Leeds United', 'Charlie Cresswell', 'Defender', 35);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (255, 'Leeds United', 'Cody Drameh', 'Defender', 37);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (256, 'Leeds United', 'Leo Fuhr Hjelde', 'Defender', 33);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (257, 'Leeds United', 'Adam Forshaw', 'Midfielder', 4);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (258, 'Leeds United', 'Stuart Dallas', 'Midfielder', 15);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (259, 'Leeds United', 'Kalvin Phillips', 'Midfielder', 23);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (260, 'Leeds United', 'Mateusz Klich', 'Midfielder', 43);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (261, 'Leeds United', 'Jamie Shackleton', 'Midfielder', 46);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (262, 'Leeds United', 'Jack Harrison', 'Midfielder', 22);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (263, 'Leeds United', 'Crysencio Summerville', 'Midfielder', 38);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (264, 'Leeds United', 'Liam McCarron', 'Midfielder', 45);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (265, 'Leeds United', 'Daniel James', 'Midfielder', 20);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (266, 'Leeds United', 'Stuart McKinstry', 'Midfielder', 39);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (267, 'Leeds United', 'Nohan Kenneh', 'Midfielder', 54);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (268, 'Leeds United', 'Patrick Bamford', 'Forward', 9);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (269, 'Leeds United', 'Tyler Roberts', 'Forward', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (270, 'Leeds United', 'Raphinha', 'Forward', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (271, 'Leeds United', 'Rodrigo', 'Forward', 19);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (272, 'Leeds United', 'Sam Greenwood', 'Forward', 42);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (273, 'Leeds United', 'Joe Gelhardt', 'Forward', 30);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (274, 'Leicester City', 'Kasper Schmeichel', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (275, 'Leicester City', 'Danny Ward', 'Goalkeeper', 12);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (276, 'Leicester City', 'Eldin Jakupovic', 'Goalkeeper', 35);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (277, 'Leicester City', 'James Justin', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (278, 'Leicester City', 'Wesley Fofana', 'Defender', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (279, 'Leicester City', 'Çaglar Söyüncü', 'Defender', 4);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (280, 'Leicester City', 'Jonny Evans', 'Defender', 6);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (281, 'Leicester City', 'Daniel Amartey', 'Defender', 18);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (282, 'Leicester City', 'Ricardo Pereira', 'Defender', 21);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (283, 'Leicester City', 'Timothy Castagne', 'Defender', 27);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (284, 'Leicester City', 'Luke Thomas', 'Defender', 33);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (285, 'Leicester City', 'Filip Benkovic', 'Defender', 34);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (286, 'Leicester City', 'Ryan Bertrand', 'Defender', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (287, 'Leicester City', 'Jannik Vestergaard', 'Defender', 23);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (288, 'Leicester City', 'Vontae Daley-Campbell', 'Defender', 38);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (289, 'Leicester City', 'Ben Nelson', 'Defender', 45);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (290, 'Leicester City', 'Youri Tielemans', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (291, 'Leicester City', 'James Maddison', 'Midfielder', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (292, 'Leicester City', 'Marc Albrighton', 'Midfielder', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (293, 'Leicester City', 'Harvey Barnes', 'Midfielder', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (294, 'Leicester City', 'Hamza Choudhury', 'Midfielder', 20);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (295, 'Leicester City', 'Nampalys Mendy', 'Midfielder', 24);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (296, 'Leicester City', 'Wilfred Ndidi', 'Midfielder', 25);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (297, 'Leicester City', 'Boubakary Soumaré', 'Midfielder', 42);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (298, 'Leicester City', 'Kiernan Dewsbury-Hall', 'Midfielder', 22);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (299, 'Leicester City', 'Thanawat Suengchitthawon', 'Midfielder', 48);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (300, 'Leicester City', 'Wanya Marcal-Madivadua', 'Midfielder', 54);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (301, 'Leicester City', 'Jamie Vardy', 'Forward', 9);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (302, 'Leicester City', 'Kelechi Iheanacho', 'Forward', 14);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (303, 'Leicester City', 'Ayoze Pérez', 'Forward', 17);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (304, 'Leicester City', 'Patson Daka', 'Forward', 29);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (305, 'Leicester City', 'Ademola Lookman', 'Forward', 37);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (306, 'Liverpool', 'Alisson', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (307, 'Liverpool', 'Adrián', 'Goalkeeper', 13);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (308, 'Liverpool', 'Caoimhin Kelleher', 'Goalkeeper', 62);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (309, 'Liverpool', 'Loris Karius', 'Goalkeeper', 22);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (310, 'Liverpool', 'Liam Hughes', 'Goalkeeper', 54);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (311, 'Liverpool', 'Marcelo Pitaluga', 'Goalkeeper', 97);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (312, 'Liverpool', 'Virgil van Dijk', 'Defender', 4);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (313, 'Liverpool', 'Joseph Gomez', 'Defender', 12);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (314, 'Liverpool', 'Konstantinos Tsimikas', 'Defender', 21);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (315, 'Liverpool', 'Andrew Robertson', 'Defender', 26);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (316, 'Liverpool', 'Joel Matip', 'Defender', 32);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (317, 'Liverpool', 'Nathaniel Phillips', 'Defender', 47);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (318, 'Liverpool', 'Trent Alexander-Arnold', 'Defender', 66);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (319, 'Liverpool', 'Neco Williams', 'Defender', 76);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (320, 'Liverpool', 'Ibrahima Konaté', 'Defender', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (321, 'Liverpool', 'Owen Beck', 'Defender', 63);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (322, 'Liverpool', 'Fabinho', 'Midfielder', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (323, 'Liverpool', 'Thiago', 'Midfielder', 6);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (324, 'Liverpool', 'James Milner', 'Midfielder', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (325, 'Liverpool', 'Naby Keïta', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (326, 'Liverpool', 'Jordan Henderson', 'Midfielder', 14);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (327, 'Liverpool', 'Alex Oxlade-Chamberlain', 'Midfielder', 15);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (328, 'Liverpool', 'Curtis Jones', 'Midfielder', 17);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (329, 'Liverpool', 'Harvey Elliott', 'Midfielder', 67);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (330, 'Liverpool', 'James Balagizi', 'Midfielder', 85);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (331, 'Liverpool', 'Tyler Morton', 'Midfielder', 80);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (332, 'Liverpool', 'Conor Bradley', 'Midfielder', 84);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (333, 'Liverpool', 'Elijah Dixon-Bonner', 'Midfielder', 45);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (334, 'Liverpool', 'Roberto Firmino', 'Forward', 9);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (335, 'Liverpool', 'Sadio Mané', 'Forward', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (336, 'Liverpool', 'Mohamed Salah', 'Forward', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (337, 'Liverpool', 'Diogo Jota', 'Forward', 20);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (338, 'Liverpool', 'Divock Origi', 'Forward', 27);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (339, 'Liverpool', 'Takumi Minamino', 'Forward', 18);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (340, 'Liverpool', 'Kaide Gordon', 'Forward', 49);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (341, 'Liverpool', 'Harvey Blair', 'Forward', 86);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (342, 'Manchester City', 'Zack Steffen', 'Goalkeeper', 13);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (343, 'Manchester City', 'Ederson', 'Goalkeeper', 31);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (344, 'Manchester City', 'Scott Carson', 'Goalkeeper', 33);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (345, 'Manchester City', 'Cieran Slicker', 'Goalkeeper', 84);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (346, 'Manchester City', 'Kyle Walker', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (347, 'Manchester City', 'Rúben Dias', 'Defender', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (348, 'Manchester City', 'John Stones', 'Defender', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (349, 'Manchester City', 'Nathan Aké', 'Defender', 6);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (350, 'Manchester City', 'Oleksandr Zinchenko', 'Defender', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (351, 'Manchester City', 'Aymeric Laporte', 'Defender', 14);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (352, 'Manchester City', 'Benjamin Mendy', 'Defender', 22);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (353, 'Manchester City', 'João Cancelo', 'Defender', 27);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (354, 'Manchester City', 'Luke Mbete', 'Defender', 79);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (355, 'Manchester City', 'Joshua Wilson-Esbrand', 'Defender', 97);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (356, 'Manchester City', 'CJ Egan-Riley', 'Defender', 56);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (357, 'Manchester City', 'Finley Burns', 'Defender', 94);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (358, 'Manchester City', 'Ilkay Gündogan', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (359, 'Manchester City', 'Rodri', 'Midfielder', 16);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (360, 'Manchester City', 'Kevin De Bruyne', 'Midfielder', 17);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (361, 'Manchester City', 'Bernardo Silva', 'Midfielder', 20);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (362, 'Manchester City', 'Fernandinho', 'Midfielder', 25);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (363, 'Manchester City', 'Phil Foden', 'Midfielder', 47);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (364, 'Manchester City', 'Jack Grealish', 'Midfielder', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (365, 'Manchester City', 'Cole Palmer', 'Midfielder', 80);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (366, 'Manchester City', 'Romeo Lavia', 'Midfielder', 90);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (367, 'Manchester City', 'James McAtee', 'Midfielder', 87);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (368, 'Manchester City', 'Raheem Sterling', 'Forward', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (369, 'Manchester City', 'Gabriel Jesus', 'Forward', 9);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (370, 'Manchester City', 'Ferran Torres', 'Forward', 21);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (371, 'Manchester City', 'Riyad Mahrez', 'Forward', 26);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (372, 'Manchester City', 'Samuel Edozie', 'Forward', 53);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (373, 'Manchester United', 'David de Gea', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (374, 'Manchester United', 'Dean Henderson', 'Goalkeeper', 26);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (375, 'Manchester United', 'Tom Heaton', 'Goalkeeper', 22);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (376, 'Manchester United', 'Lee Grant', 'Goalkeeper', 13);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (377, 'Manchester United', 'Matej Kovar', 'Goalkeeper', 51);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (378, 'Manchester United', 'Victor Lindelöf', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (379, 'Manchester United', 'Eric Bailly', 'Defender', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (380, 'Manchester United', 'Phil Jones', 'Defender', 4);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (381, 'Manchester United', 'Harry Maguire', 'Defender', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (382, 'Manchester United', 'Luke Shaw', 'Defender', 23);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (383, 'Manchester United', 'Alex Telles', 'Defender', 27);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (384, 'Manchester United', 'Aaron Wan-Bissaka', 'Defender', 29);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (385, 'Manchester United', 'Diogo Dalot', 'Defender', 20);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (386, 'Manchester United', 'Teden Mengi', 'Defender', 43);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (387, 'Manchester United', 'Raphaël Varane', 'Defender', 19);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (388, 'Manchester United', 'Paul Pogba', 'Midfielder', 6);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (389, 'Manchester United', 'Fred', 'Midfielder', 17);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (390, 'Manchester United', 'Bruno Fernandes', 'Midfielder', 18);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (391, 'Manchester United', 'Nemanja Matic', 'Midfielder', 31);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (392, 'Manchester United', 'Donny van de Beek', 'Midfielder', 34);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (393, 'Manchester United', 'Scott McTominay', 'Midfielder', 39);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (394, 'Manchester United', 'Hannibal Mejbri', 'Midfielder', 46);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (395, 'Manchester United', 'Jesse Lingard', 'Midfielder', 14);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (396, 'Manchester United', 'Juan Mata', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (397, 'Manchester United', 'Facundo Pellistri', 'Midfielder', 28);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (398, 'Manchester United', 'Edinson Cavani', 'Forward', 21);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (399, 'Manchester United', 'Anthony Martial', 'Forward', 9);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (400, 'Manchester United', 'Marcus Rashford', 'Forward', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (401, 'Manchester United', 'Mason Greenwood', 'Forward', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (402, 'Manchester United', 'Amad Diallo', 'Forward', 16);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (403, 'Manchester United', 'Anthony Elanga', 'Forward', 36);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (404, 'Manchester United', 'Shola Shoretire', 'Forward', 47);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (405, 'Manchester United', 'Jadon Sancho', 'Forward', 25);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (406, 'Manchester United', 'Cristiano Ronaldo', 'Forward', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (407, 'Newcastle United', 'Martin Dúbravka', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (408, 'Newcastle United', 'Karl Darlow', 'Goalkeeper', 26);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (409, 'Newcastle United', 'Mark Gillespie', 'Goalkeeper', 29);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (410, 'Newcastle United', 'Daniel Langley', 'Goalkeeper', 33);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (411, 'Newcastle United', 'Freddie Woodman', 'Goalkeeper', 27);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (412, 'Newcastle United', 'Ciaran Clark', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (413, 'Newcastle United', 'Paul Dummett', 'Defender', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (414, 'Newcastle United', 'Fabian Schär', 'Defender', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (415, 'Newcastle United', 'Jamaal Lascelles', 'Defender', 6);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (416, 'Newcastle United', 'Jamal Lewis', 'Defender', 12);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (417, 'Newcastle United', 'Emil Krafth', 'Defender', 17);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (418, 'Newcastle United', 'Federico Fernández', 'Defender', 18);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (419, 'Newcastle United', 'Javier Manquillo', 'Defender', 19);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (420, 'Newcastle United', 'Jonjo Shelvey', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (421, 'Newcastle United', 'Matt Ritchie', 'Midfielder', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (422, 'Newcastle United', 'Isaac Hayden', 'Midfielder', 14);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (423, 'Newcastle United', 'Jeff Hendrick', 'Midfielder', 16);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (424, 'Newcastle United', 'Ryan Fraser', 'Midfielder', 21);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (425, 'Newcastle United', 'Jacob Murphy', 'Midfielder', 23);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (426, 'Newcastle United', 'Miguel Almirón', 'Midfielder', 24);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (427, 'Newcastle United', 'Sean Longstaff', 'Midfielder', 36);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (428, 'Newcastle United', 'Elliot Anderson', 'Midfielder', 32);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (429, 'Newcastle United', 'Joseph Willock', 'Midfielder', 28);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (430, 'Newcastle United', 'Joe White', 'Midfielder', 56);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (431, 'Newcastle United', 'Joelinton', 'Forward', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (432, 'Newcastle United', 'Allan Saint-Maximin', 'Forward', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (433, 'Newcastle United', 'Dwight Gayle', 'Forward', 34);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (434, 'Newcastle United', 'Callum Wilson', 'Forward', 9);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (435, 'Norwich City', 'Tim Krul', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (436, 'Norwich City', 'Michael McGovern', 'Goalkeeper', 33);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (437, 'Norwich City', 'Angus Gunn', 'Goalkeeper', 28);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (438, 'Norwich City', 'Max Aarons', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (439, 'Norwich City', 'Sam Byram', 'Defender', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (440, 'Norwich City', 'Grant Hanley', 'Defender', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (441, 'Norwich City', 'Christoph Zimmermann', 'Defender', 6);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (442, 'Norwich City', 'Bali Mumba', 'Defender', 26);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (443, 'Norwich City', 'Andrew Omobamidele', 'Defender', 44);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (444, 'Norwich City', 'Ben Gibson', 'Defender', 4);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (445, 'Norwich City', 'Dimitris Giannoulis', 'Defender', 30);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (446, 'Norwich City', 'Brandon Williams', 'Defender', 21);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (447, 'Norwich City', 'Ozan Kabak', 'Defender', 15);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (448, 'Norwich City', 'Lukas Rupp', 'Midfielder', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (449, 'Norwich City', 'Kieran Dowell', 'Midfielder', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (450, 'Norwich City', 'Przemyslaw Placheta', 'Midfielder', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (451, 'Norwich City', 'Todd Cantwell', 'Midfielder', 14);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (452, 'Norwich City', 'Jacob Sørensen', 'Midfielder', 19);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (453, 'Norwich City', 'Kenny McLean', 'Midfielder', 23);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (454, 'Norwich City', 'Milot Rashica', 'Midfielder', 17);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (455, 'Norwich City', 'Billy Gilmour', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (456, 'Norwich City', 'Pierre Lees-Melou', 'Midfielder', 20);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (457, 'Norwich City', 'Mathias Normann', 'Midfielder', 16);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (458, 'Norwich City', 'Teemu Pukki', 'Forward', 22);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (459, 'Norwich City', 'Adam Idah', 'Forward', 35);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (460, 'Norwich City', 'Joshua Sargent', 'Forward', 24);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (461, 'Norwich City', 'Christos Tzolis', 'Forward', 18);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (462, 'Southampton', 'Alex McCarthy', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (463, 'Southampton', 'Harry Lewis', 'Goalkeeper', 41);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (464, 'Southampton', 'Fraser Forster', 'Goalkeeper', 44);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (465, 'Southampton', 'Kyle Walker-Peters', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (466, 'Southampton', 'Jack Stephens', 'Defender', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (467, 'Southampton', 'Mohammed Salisu', 'Defender', 22);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (468, 'Southampton', 'Jan Bednarek', 'Defender', 35);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (469, 'Southampton', 'Yan Valery', 'Defender', 43);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (470, 'Southampton', 'Romain Perraud', 'Defender', 15);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (471, 'Southampton', 'Valentino Livramento', 'Defender', 21);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (472, 'Southampton', 'Thierry Small', 'Defender', 16);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (473, 'Southampton', 'Lyanco', 'Defender', 4);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (474, 'Southampton', 'Oriol Romeu', 'Midfielder', 6);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (475, 'Southampton', 'James Ward-Prowse', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (476, 'Southampton', 'Nathan Redmond', 'Midfielder', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (477, 'Southampton', 'Moussa Djenepo', 'Midfielder', 19);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (478, 'Southampton', 'Stuart Armstrong', 'Midfielder', 17);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (479, 'Southampton', 'William Smallbone', 'Midfielder', 20);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (480, 'Southampton', 'Nathan Tella', 'Midfielder', 23);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (481, 'Southampton', 'Ibrahima Diallo', 'Midfielder', 27);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (482, 'Southampton', 'Mohamed Elyounoussi', 'Midfielder', 24);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (483, 'Southampton', 'Che Adams', 'Forward', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (484, 'Southampton', 'Shane Long', 'Forward', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (485, 'Southampton', 'Theo Walcott', 'Forward', 32);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (486, 'Southampton', 'Armando Broja', 'Forward', 18);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (487, 'Southampton', 'Adam Armstrong', 'Forward', 9);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (488, 'Tottenham Hotspur', 'Hugo Lloris', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (489, 'Tottenham Hotspur', 'Pierluigi Gollini', 'Goalkeeper', 22);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (490, 'Tottenham Hotspur', 'Brandon Austin', 'Goalkeeper', 40);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (491, 'Tottenham Hotspur', 'Matt Doherty', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (492, 'Tottenham Hotspur', 'Sergio Reguilón', 'Defender', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (493, 'Tottenham Hotspur', 'Davinson Sánchez', 'Defender', 6);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (494, 'Tottenham Hotspur', 'Joe Rodon', 'Defender', 14);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (495, 'Tottenham Hotspur', 'Japhet Tanganga', 'Defender', 25);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (496, 'Tottenham Hotspur', 'Ben Davies', 'Defender', 33);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (497, 'Tottenham Hotspur', 'Eric Dier', 'Defender', 15);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (498, 'Tottenham Hotspur', 'Cristian Romero', 'Defender', 4);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (499, 'Tottenham Hotspur', 'Maksim Paskotsi', 'Defender', 48);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (500, 'Tottenham Hotspur', 'Kallum Cesay', 'Defender', 50);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (501, 'Tottenham Hotspur', 'Brooklyn Lyons-Foster', 'Defender', 53);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (502, 'Tottenham Hotspur', 'Emerson Royal', 'Defender', 12);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (503, 'Tottenham Hotspur', 'Tobi Omole', 'Defender', 49);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (504, 'Tottenham Hotspur', 'Malachi Fagan-Walcott', 'Defender', 46);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (505, 'Tottenham Hotspur', 'Pierre-Emile Højbjerg', 'Midfielder', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (506, 'Tottenham Hotspur', 'Harry Winks', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (507, 'Tottenham Hotspur', 'Giovani Lo Celso', 'Midfielder', 18);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (508, 'Tottenham Hotspur', 'Dele Alli', 'Midfielder', 20);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (509, 'Tottenham Hotspur', 'Tanguy Ndombele', 'Midfielder', 28);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (510, 'Tottenham Hotspur', 'Ryan Sessegnon', 'Midfielder', 19);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (511, 'Tottenham Hotspur', 'Oliver Skipp', 'Midfielder', 29);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (512, 'Tottenham Hotspur', 'Harvey White', 'Midfielder', 42);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (513, 'Tottenham Hotspur', 'Nile John', 'Midfielder', 43);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (514, 'Tottenham Hotspur', 'Matthew Craig', 'Midfielder', 51);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (515, 'Tottenham Hotspur', 'Romaine Mundle', 'Midfielder', 55);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (516, 'Tottenham Hotspur', 'Michael Craig', 'Midfielder', 52);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (517, 'Tottenham Hotspur', 'Son Heung-Min', 'Forward', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (518, 'Tottenham Hotspur', 'Harry Kane', 'Forward', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (519, 'Tottenham Hotspur', 'Steven Bergwijn', 'Forward', 23);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (520, 'Tottenham Hotspur', 'Lucas Moura', 'Forward', 27);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (521, 'Tottenham Hotspur', 'Jack Clarke', 'Forward', 47);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (522, 'Tottenham Hotspur', 'Bryan Gil', 'Forward', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (523, 'Tottenham Hotspur', 'Dane Scarlett', 'Forward', 44);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (524, 'Tottenham Hotspur', 'Dilan Markanday', 'Forward', 54);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (525, 'Watford', 'Ben Foster', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (526, 'Watford', 'Daniel Bachmann', 'Goalkeeper', 26);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (527, 'Watford', 'Robert Elliot', 'Goalkeeper', 35);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (528, 'Watford', 'Jeremy Ngakia', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (529, 'Watford', 'William Troost-Ekong', 'Defender', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (530, 'Watford', 'Adam Masina', 'Defender', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (531, 'Watford', 'Craig Cathcart', 'Defender', 15);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (532, 'Watford', 'Kiko Femenía', 'Defender', 21);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (533, 'Watford', 'Christian Kabasele', 'Defender', 27);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (534, 'Watford', 'Francisco Sierralta', 'Defender', 31);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (535, 'Watford', 'Danny Rose', 'Defender', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (536, 'Watford', 'James Morris', 'Defender', 42);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (537, 'Watford', 'Nicolas Nkoulou', 'Defender', 13);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (538, 'Watford', 'Tom Cleverley', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (539, 'Watford', 'Ken Sema', 'Midfielder', 12);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (540, 'Watford', 'Dan Gosling', 'Midfielder', 16);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (541, 'Watford', 'Daniel Phillips', 'Midfielder', 52);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (542, 'Watford', 'Imran Louza', 'Midfielder', 6);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (543, 'Watford', 'Ignacio Pussetto', 'Midfielder', 33);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (544, 'Watford', 'Peter Etebo', 'Midfielder', 4);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (545, 'Watford', 'Kwadwo Baah', 'Midfielder', 34);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (546, 'Watford', 'Juraj Kucka', 'Midfielder', 33);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (547, 'Watford', 'Ozan Tufan', 'Midfielder', 18);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (548, 'Watford', 'Moussa Sissoko', 'Midfielder', 19);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (549, 'Watford', 'João Pedro', 'Forward', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (550, 'Watford', 'Ismaila Sarr', 'Forward', 23);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (551, 'Watford', 'Emmanuel Dennis', 'Forward', 25);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (552, 'Watford', 'Ashley Fletcher', 'Forward', 17);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (553, 'Watford', 'Joshua King', 'Forward', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (554, 'Watford', 'Cucho Hernández', 'Forward', 29);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (555, 'West Ham United', 'Lukasz Fabianski', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (556, 'West Ham United', 'David Martin', 'Goalkeeper', 25);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (557, 'West Ham United', 'Darren Randolph', 'Goalkeeper', 35);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (558, 'West Ham United', 'Alphonse Areola', 'Goalkeeper', 13);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (559, 'West Ham United', 'Aaron Cresswell', 'Defender', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (560, 'West Ham United', 'Vladimir Coufal', 'Defender', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (561, 'West Ham United', 'Angelo Ogbonna', 'Defender', 21);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (562, 'West Ham United', 'Issa Diop', 'Defender', 23);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (563, 'West Ham United', 'Ryan Fredericks', 'Defender', 24);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (564, 'West Ham United', 'Arthur Masuaku', 'Defender', 26);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (565, 'West Ham United', 'Craig Dawson', 'Defender', 15);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (566, 'West Ham United', 'Winston Reid', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (567, 'West Ham United', 'Jamal Baptiste', 'Defender', 75);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (568, 'West Ham United', 'Kurt Zouma', 'Defender', 4);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (569, 'West Ham United', 'Ajibola Alese', 'Defender', 42);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (570, 'West Ham United', 'Ben Johnson', 'Defender', 31);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (571, 'West Ham United', 'Harrison Ashby', 'Defender', 50);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (572, 'West Ham United', 'Manuel Lanzini', 'Midfielder', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (573, 'West Ham United', 'Mark Noble', 'Midfielder', 16);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (574, 'West Ham United', 'Pablo Fornals', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (575, 'West Ham United', 'Tomas Soucek', 'Midfielder', 28);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (576, 'West Ham United', 'Declan Rice', 'Midfielder', 41);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (577, 'West Ham United', 'Nikola Vlasic', 'Midfielder', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (578, 'West Ham United', 'Alex Král', 'Midfielder', 33);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (579, 'West Ham United', 'Daniel Chesters', 'Midfielder', 51);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (580, 'West Ham United', 'Andriy Yarmolenko', 'Forward', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (581, 'West Ham United', 'Saïd Benrahma', 'Forward', 22);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (582, 'West Ham United', 'Jarrod Bowen', 'Forward', 20);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (583, 'West Ham United', 'Michail Antonio', 'Forward', 9);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (584, 'Wolverhampton Wanderers', 'John Ruddy', 'Goalkeeper', 21);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (585, 'Wolverhampton Wanderers', 'José Sá', 'Goalkeeper', 1);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (586, 'Wolverhampton Wanderers', 'Louie Moulden', 'Goalkeeper', 13);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (587, 'Wolverhampton Wanderers', 'James Storer', 'Goalkeeper', 48);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (588, 'Wolverhampton Wanderers', 'Ki-Jana Hoever', 'Defender', 2);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (589, 'Wolverhampton Wanderers', 'Marçal', 'Defender', 5);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (590, 'Wolverhampton Wanderers', 'Willy Boly', 'Defender', 15);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (591, 'Wolverhampton Wanderers', 'Conor Coady', 'Defender', 16);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (592, 'Wolverhampton Wanderers', 'Jonny', 'Defender', 19);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (593, 'Wolverhampton Wanderers', 'Nélson Semedo', 'Defender', 22);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (594, 'Wolverhampton Wanderers', 'Maximilian Kilman', 'Defender', 23);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (595, 'Wolverhampton Wanderers', 'Yerson Mosquera', 'Defender', 14);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (596, 'Wolverhampton Wanderers', 'Rayan Aït-Nouri', 'Defender', 3);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (597, 'Wolverhampton Wanderers', 'Rúben Neves', 'Midfielder', 8);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (598, 'Wolverhampton Wanderers', 'Daniel Podence', 'Midfielder', 10);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (599, 'Wolverhampton Wanderers', 'Romain Saïss', 'Midfielder', 27);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (600, 'Wolverhampton Wanderers', 'João Moutinho', 'Midfielder', 28);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (601, 'Wolverhampton Wanderers', 'Leander Dendoncker', 'Midfielder', 32);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (602, 'Wolverhampton Wanderers', 'Luke Cundle', 'Midfielder', 39);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (603, 'Wolverhampton Wanderers', 'Pedro Neto', 'Forward', 7);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (604, 'Wolverhampton Wanderers', 'Raúl Jiménez', 'Forward', 9);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (605, 'Wolverhampton Wanderers', 'Fábio Silva', 'Forward', 17);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (606, 'Wolverhampton Wanderers', 'Adama Traoré', 'Forward', 37);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (607, 'Wolverhampton Wanderers', 'Trincão', 'Forward', 11);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (608, 'Wolverhampton Wanderers', 'Chem Campbell', 'Forward', 77);
INSERT INTO jatekosok(id, club, name, position, number) VALUES (609, 'Wolverhampton Wanderers', 'Hwang Hee-Chan', 'Forward', 26);
