INSERT INTO Stadion(team, name) VALUES ('Arsenal', 'Emirates Stadium');
INSERT INTO Stadion(team, name) VALUES ('Aston Villa', 'Villa Park');
INSERT INTO Stadion(team, name) VALUES ('Brentford', 'Brentford Community Stadium');
INSERT INTO Stadion(team, name) VALUES ('Brighton and Hove Albion', 'American Express Community Stadium');
INSERT INTO Stadion(team, name) VALUES ('Burnley', 'Turf Moor');
INSERT INTO Stadion(team, name) VALUES ('Chelsea', 'Stamford Bridge');
INSERT INTO Stadion(team, name) VALUES ('Crystal Palace', 'Selhurst Park Stadium');
INSERT INTO Stadion(team, name) VALUES ('Everton', 'Goodison Park');
INSERT INTO Stadion(team, name) VALUES ('Leeds United', 'Elland Road');
INSERT INTO Stadion(team, name) VALUES ('Leicester City', 'King Power Stadium');
INSERT INTO Stadion(team, name) VALUES ('Liverpool', 'Anfield');
INSERT INTO Stadion(team, name) VALUES ('Manchester City', 'Eithad Stadium');
INSERT INTO Stadion(team, name) VALUES ('Manchester United', 'Old Trafford');
INSERT INTO Stadion(team, name) VALUES ('Newcastle United', 'St. James'' Park');
INSERT INTO Stadion(team, name) VALUES ('Norwich City', 'Carrow Road Stadium');
INSERT INTO Stadion(team, name) VALUES ('Southampton', 'Saint Mary''s Stadium');
INSERT INTO Stadion(team, name) VALUES ('Tottenham Hotspur', 'Tottenham Hotspur Stadium');
INSERT INTO Stadion(team, name) VALUES ('Watford', 'Vicarage Road Stadium');
INSERT INTO Stadion(team, name) VALUES ('West Ham United', 'London Stadium');
INSERT INTO Stadion(team, name) VALUES ('Wolverhampton Wanderers', 'Molineux Stadium');