DROP TRIGGER IF EXISTS calculate_points_matches_on_insert;
DROP TRIGGER IF EXISTS calculate_points_matches_on_update;
DROP TABLE IF EXISTS Stadiums CASCADE;
DROP TABLE IF EXISTS Managers CASCADE;
DROP TABLE IF EXISTS Scorers CASCADE;
DROP TABLE IF EXISTS Matches CASCADE;
DROP TABLE IF EXISTS Players CASCADE;
DROP TABLE IF EXISTS Owners CASCADE;
DROP TABLE IF EXISTS Clubs CASCADE;
DROP TABLE IF EXISTS Championship CASCADE;

