SET FOREIGN_KEY_CHECKS = 0;
SET GLOBAL FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS stadion CASCADE;
DROP TABLE IF EXISTS jatekosok CASCADE;
DROP TABLE IF EXISTS meccsek CASCADE;
DROP TABLE IF EXISTS csapatok CASCADE;
