INSERT INTO Stadiums(team, name, city) VALUES ('Arsenal', 'Emirates Stadium', 'London');
INSERT INTO Stadiums(team, name, city) VALUES ('Aston Villa', 'Villa Park', 'Birmingham');
INSERT INTO Stadiums(team, name, city) VALUES ('Brentford', 'Brentford Community Stadium', 'London');
INSERT INTO Stadiums(team, name, city) VALUES ('Brighton and Hove Albion', 'American Express Community Stadium', 'Brigthon');
INSERT INTO Stadiums(team, name, city) VALUES ('Burnley', 'Turf Moor', 'Burnley');
INSERT INTO Stadiums(team, name, city) VALUES ('Chelsea', 'Stamford Bridge', 'London');
INSERT INTO Stadiums(team, name, city) VALUES ('Crystal Palace', 'Selhurst Park Stadium', 'London');
INSERT INTO Stadiums(team, name, city) VALUES ('Everton', 'Goodison Park', 'Liverpool');
INSERT INTO Stadiums(team, name, city) VALUES ('Leeds United', 'Elland Road', 'Leeds');
INSERT INTO Stadiums(team, name, city) VALUES ('Leicester City', 'King Power Stadium', 'Leicester');
INSERT INTO Stadiums(team, name, city) VALUES ('Liverpool', 'Anfield', 'Liverpool');
INSERT INTO Stadiums(team, name, city) VALUES ('Manchester City', 'Eithad Stadium', 'Manchester');
INSERT INTO Stadiums(team, name, city) VALUES ('Manchester United', 'Old Trafford', 'Manchester');
INSERT INTO Stadiums(team, name, city) VALUES ('Newcastle United', 'St. James'' Park', 'Newcastle');
INSERT INTO Stadiums(team, name, city) VALUES ('Norwich City', 'Carrow Road Stadium', 'Norwich');
INSERT INTO Stadiums(team, name, city) VALUES ('Southampton', 'Saint Mary''s Stadium', 'Southampton');
INSERT INTO Stadiums(team, name, city) VALUES ('Tottenham Hotspur', 'Tottenham Hotspur Stadium', 'London');
INSERT INTO Stadiums(team, name, city) VALUES ('Watford', 'Vicarage Road Stadium', 'Watford');
INSERT INTO Stadiums(team, name, city) VALUES ('West Ham United', 'London Stadium', 'London');
INSERT INTO Stadiums(team, name, city) VALUES ('Wolverhampton Wanderers', 'Molineux Stadium', 'Wolverhampton');