INSERT INTO Scorers(name, team, league, goals) VALUES ('Mohamed Salah', 'Liverpool', 'Premier League', 10);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Jamie Vardy', 'Leicester City', 'Premier League', 7);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Michail Antonio', 'West Ham United', 'Premier League', 6);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Sadio Mané', 'Liverpool', 'Premier League', 6);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Raphinha', 'Leeds United', 'Premier League', 4);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Pierre-Emerick Aubameyang', 'Arsenal', 'Premier League', 4);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Roberto Firmino', 'Liverpool', 'Premier League', 4);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Bruno Fernandes', 'Manchester United', 'Premier League', 4);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Maxwel Cornet', 'Burnley', 'Premier League', 4);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Cristiano Ronaldo', 'Manchester United', 'Premier League', 4);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Pablo Fornals', 'West Ham United', 'Premier League', 4);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Conor Gallagher', 'Crystal Palace', 'Premier League', 4);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Mason Greenwood', 'Manchester United', 'Premier League', 4);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Hwang Hee-Chan', 'Wolverhampton Wanderers', 'Premier League', 4);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Reece James', 'Chelsea', 'Premier League', 4);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Neal Maupay', 'Brighton and Hove Albion', 'Premier League', 4);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Ismaila Sarr', 'Watford', 'Premier League', 4);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Emile Smith Rowe', 'Arsenal', 'Premier League', 4);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Son Heung-Min', 'Tottenham Hotspur', 'Premier League', 4);
INSERT INTO Scorers(name, team, league, goals) VALUES ('Diogo Jota', 'Liverpool', 'Premier League', 4);