INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Bernd Leno', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Arthur Okonkwo', 'Goalkeeper', 33, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Karl Hein', 'Goalkeeper', 49, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Aaron Ramsdale', 'Goalkeeper', 32, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Kieran Tierney', 'Defender', 3, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Gabriel Magalhães', 'Defender', 6, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Rob Holding', 'Defender', 16, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Cédric Soares', 'Defender', 17, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Calum Chambers', 'Defender', 21, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Pablo Marí', 'Defender', 22, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Sead Kolasinac', 'Defender', 31, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Nuno Tavares', 'Defender', 20, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Benjamin White', 'Defender', 4, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Takehiro Tomiyasu', 'Defender', 18, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Bukayo Saka', 'Midfielder', 7, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Thomas Partey', 'Midfielder', 5, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Mohamed Elneny', 'Midfielder', 25, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Emile Smith Rowe', 'Midfielder', 10, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Granit Xhaka', 'Midfielder', 34, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Ainsley Maitland-Niles', 'Midfielder', 15, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Albert Sambi Lokonga', 'Midfielder', 23, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Martin Ødegaard', 'Midfielder', 8, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Salah-Eddine Oulad M"hand', 'Midfielder', 65, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Alexandre Lacazette', 'Forward', 9, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Pierre-Emerick Aubameyang', 'Forward', 14, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Nicolas Pépé', 'Forward', 19, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Eddie Nketiah', 'Forward', 30, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Gabriel Martinelli', 'Forward', 35, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Arsenal', 'Folarin Balogun', 'Forward', 26, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Jed Steer', 'Goalkeeper', 12, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Emiliano Martínez', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Viljami Sinisalo', 'Goalkeeper', 38, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Matthew Cash', 'Defender', 2, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Ezri Konsa', 'Defender', 4, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Tyrone Mings', 'Defender', 5, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Matt Targett', 'Defender', 3, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Kortney Hause', 'Defender', 30, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Ashley Young', 'Defender', 18, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Axel Tuanzebe', 'Defender', 16, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Sil Swinkels', 'Defender', 50, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Douglas Luiz', 'Midfielder', 6, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'John McGinn', 'Midfielder', 7, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Trézéguet', 'Midfielder', 17, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Marvelous Nakamba', 'Midfielder', 19, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Anwar El Ghazi', 'Midfielder', 21, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Morgan Sanson', 'Midfielder', 8, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Jacob Ramsey', 'Midfielder', 41, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Keinan Davis', 'Midfielder', 39, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Emiliano Buendía', 'Midfielder', 10, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Jaden Philogene-Bidace', 'Midfielder', 32, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Carney Chukwuemeka', 'Midfielder', 33, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Aaron Ramsey', 'Midfielder', 40, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Lamare Bogarde', 'Midfielder', 36, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Hayden Lindley', 'Midfielder', 49, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Ollie Watkins', 'Forward', 11, 3);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Bertrand Traoré', 'Forward', 15, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Leon Bailey', 'Forward', 31, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Danny Ings', 'Forward', 20, 3);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Caleb Chukwuemeka', 'Forward', 46, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Aston Villa', 'Cameron Archer', 'Forward', 35, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'David Raya', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Álvaro Fernández', 'Goalkeeper', 40, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Matthew Cox', 'Goalkeeper', 41, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Rico Henry', 'Defender', 3, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Charlie Goode', 'Defender', 4, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Ethan Pinnock', 'Defender', 5, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Pontus Jansson', 'Defender', 18, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Mads Bech Sørensen', 'Defender', 29, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Mads Roerslev', 'Defender', 30, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Dominic Thompson', 'Defender', 2, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Julian Jeanvier', 'Defender', 23, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Luka Racic', 'Defender', 32, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Finley Stevens', 'Defender', 36, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Lewis Gordon', 'Defender', 39, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Kristoffer Ajer', 'Defender', 20, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Zanka', 'Defender', 22, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Daniel Oyegoke', 'Defender', 34, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Christian Nørgaard', 'Midfielder', 6, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Mathias Jensen', 'Midfielder', 8, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Josh Dasilva', 'Midfielder', 10, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Bryan Mbeumo', 'Midfielder', 19, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Tariqe Fosu-Henry', 'Midfielder', 24, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Shandon Baptiste', 'Midfielder', 26, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Vitaly Janelt', 'Midfielder', 27, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Jan Zamburek', 'Midfielder', 31, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Mads Bidstrup', 'Midfielder', 28, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Maxwell Haygarth', 'Midfielder', 37, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Frank Onyeka', 'Midfielder', 15, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Myles Peart-Harris', 'Midfielder', 25, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Yoane Wissa', 'Midfielder', 11, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Paris Maghoma', 'Midfielder', 33, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Sergi Canós', 'Forward', 7, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Marcus Forss', 'Forward', 9, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Ivan Toney', 'Forward', 17, 3);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brentford', 'Saman Ghoddos', 'Forward', 14, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Jason Steele', 'Goalkeeper', 23, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Robert Sánchez', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Kjell Scherpen', 'Goalkeeper', 16, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Thomas McGill', 'Goalkeeper', 38, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Tariq Lamptey', 'Defender', 2, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Adam Webster', 'Defender', 4, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Lewis Dunk', 'Defender', 5, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Dan Burn', 'Defender', 33, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Joël Veltman', 'Defender', 34, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Shane Duffy', 'Defender', 24, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Haydon Roberts', 'Defender', 28, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'James Furlong', 'Defender', 54, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Odeluga Offiah', 'Defender', 57, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Antef Tsoungui', 'Defender', 53, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Marc Cucurella', 'Defender', 3, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Tudor Baluta', 'Defender', 35, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Ed Turns', 'Defender', 55, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Yves Bissouma', 'Midfielder', 8, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Alexis Mac Allister', 'Midfielder', 10, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Pascal Groß', 'Midfielder', 13, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Adam Lallana', 'Midfielder', 14, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Jakub Moder', 'Midfielder', 15, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Steven Alzate', 'Midfielder', 17, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Solly March', 'Midfielder', 20, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Enock Mwepu', 'Midfielder', 12, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Taylor Richards', 'Midfielder', 30, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Marc Leonard', 'Midfielder', 42, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Andrew Moran', 'Midfielder', 59, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Aaron Connolly', 'Forward', 7, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Neal Maupay', 'Forward', 9, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Leandro Trossard', 'Forward', 11, 3);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Danny Welbeck', 'Forward', 18, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Evan Ferguson', 'Forward', 58, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Jürgen Locadia', 'Forward', 27, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Brighton and Hove Albion', 'Jeremy Sarmiento', 'Forward', 60, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Nick Pope', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Will Norris', 'Goalkeeper', 25, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Wayne Hennessey', 'Goalkeeper', 13, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Matthew Lowton', 'Defender', 2, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Charlie Taylor', 'Defender', 3, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'James Tarkowski', 'Defender', 5, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Ben Mee', 'Defender', 6, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Erik Pieters', 'Defender', 23, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Phil Bardsley', 'Defender', 26, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Kevin Long', 'Defender', 28, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Nathan Collins', 'Defender', 22, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Bobby Thomas', 'Defender', 37, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Owen Dodgson', 'Defender', 39, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Connor Roberts', 'Defender', 14, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Jack Cork', 'Midfielder', 4, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Jóhann Gudmundsson', 'Midfielder', 7, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Josh Brownhill', 'Midfielder', 8, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Dwight McNeil', 'Midfielder', 11, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Dale Stephens', 'Midfielder', 16, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Ashley Westwood', 'Midfielder', 18, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Matej Vydra', 'Midfielder', 27, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Lewis Richardson', 'Midfielder', 38, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Aaron Lennon', 'Midfielder', 17, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Maxwel Cornet', 'Midfielder', 20, 5);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Chris Wood', 'Forward', 9, 3);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Ashley Barnes', 'Forward', 10, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Burnley', 'Jay Rodriguez', 'Forward', 19, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Kepa Arrizabalaga', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Édouard Mendy', 'Goalkeeper', 16, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Marcus Bettinelli', 'Goalkeeper', 13, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Lucas Bergström', 'Goalkeeper', 36, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Antonio Rüdiger', 'Defender', 2, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Marcos Alonso', 'Defender', 3, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Andreas Christensen', 'Defender', 4, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Thiago Silva', 'Defender', 6, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Ben Chilwell', 'Defender', 21, 3);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Reece James', 'Defender', 24, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'César Azpilicueta', 'Defender', 28, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Trevoh Chalobah', 'Defender', 14, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Malang Sarr', 'Defender', 31, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Xavier Mbuyamba', 'Defender', 43, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Jorginho', 'Midfielder', 5, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'N"Golo Kanté', 'Midfielder', 7, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Christian Pulisic', 'Midfielder', 10, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Mateo Kovacic', 'Midfielder', 8, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Mason Mount', 'Midfielder', 19, 3);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Hakim Ziyech', 'Midfielder', 22, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Kai Havertz', 'Midfielder', 29, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Ruben Loftus-Cheek', 'Midfielder', 12, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Saúl Ñíguez', 'Midfielder', 17, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Ross Barkley', 'Midfielder', 18, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Timo Werner', 'Forward', 11, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Callum Hudson-Odoi', 'Forward', 20, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Chelsea', 'Romelu Lukaku', 'Forward', 9, 3);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Jack Butland', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Vicente Guaita', 'Goalkeeper', 13, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Remi Matthews', 'Goalkeeper', 19, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Joel Ward', 'Defender', 2, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'James Tomkins', 'Defender', 5, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Nathaniel Clyne', 'Defender', 17, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Tyrick Mitchell', 'Defender', 3, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Martin Kelly', 'Defender', 34, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Nathan Ferguson', 'Defender', 36, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Marc Guéhi', 'Defender', 6, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Joachim Andersen', 'Defender', 16, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Reece Hannam', 'Defender', 43, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Luka Milivojevic', 'Midfielder', 4, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Cheikhou Kouyaté', 'Midfielder', 8, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Jeffrey Schlupp', 'Midfielder', 15, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'James McArthur', 'Midfielder', 18, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Eberechi Eze', 'Midfielder', 10, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Jairo Riedewald', 'Midfielder', 44, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Michael Olise', 'Midfielder', 7, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Conor Gallagher', 'Midfielder', 23, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Jesurun Rak-Sakyi', 'Midfielder', 49, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Will Hughes', 'Midfielder', 12, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Jordan Ayew', 'Forward', 9, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Wilfried Zaha', 'Forward', 11, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Jean-Philippe Mateta', 'Forward', 14, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Christian Benteke', 'Forward', 20, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Robert Street', 'Forward', 46, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Scott Banks', 'Forward', 40, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Crystal Palace', 'Odsonne Édouard', 'Forward', 22, 3);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Jordan Pickford', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Asmir Begovic', 'Goalkeeper', 15, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Andy Lonergan', 'Goalkeeper', 31, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Harry Tyrer', 'Goalkeeper', 53, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Mason Holgate', 'Defender', 4, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Michael Keane', 'Defender', 5, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Lucas Digne', 'Defender', 12, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Yerry Mina', 'Defender', 13, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Ben Godfrey', 'Defender', 22, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Séamus Coleman', 'Defender', 23, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Jonjoe Kenny', 'Defender', 2, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Jarrad Branthwaite', 'Defender', 32, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Reece Welch', 'Defender', 64, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Allan', 'Midfielder', 6, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Fabian Delph', 'Midfielder', 8, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Gylfi Sigurdsson', 'Midfielder', 10, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Abdoulaye Doucouré', 'Midfielder', 16, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'André Gomes', 'Midfielder', 21, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Jean-Philippe Gbamin', 'Midfielder', 25, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Tom Davies', 'Midfielder', 26, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Andros Townsend', 'Midfielder', 14, 3);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Charlie Whitaker', 'Midfielder', 57, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Tyler Onyango', 'Midfielder', 62, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Richarlison', 'Forward', 7, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Dominic Calvert-Lewin', 'Forward', 9, 3);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Alex Iwobi', 'Forward', 17, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Cenk Tosun', 'Forward', 20, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Demarai Gray', 'Forward', 11, 3);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Anthony Gordon', 'Forward', 24, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Salomón Rondón', 'Forward', 33, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Ellis Simms', 'Forward', 50, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Everton', 'Lewis Dobbin', 'Forward', 61, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Illan Meslier', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Kristoffer Klaesson', 'Goalkeeper', 13, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Luke Ayling', 'Defender', 2, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Robin Koch', 'Defender', 5, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Liam Cooper', 'Defender', 6, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Diego Llorente', 'Defender', 14, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Pascal Struijk', 'Defender', 21, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Laurens De Bock', 'Defender', 12, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Junior Firpo', 'Defender', 3, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Charlie Cresswell', 'Defender', 35, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Cody Drameh', 'Defender', 37, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Leo Fuhr Hjelde', 'Defender', 33, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Adam Forshaw', 'Midfielder', 4, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Stuart Dallas', 'Midfielder', 15, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Kalvin Phillips', 'Midfielder', 23, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Mateusz Klich', 'Midfielder', 43, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Jamie Shackleton', 'Midfielder', 46, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Jack Harrison', 'Midfielder', 22, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Crysencio Summerville', 'Midfielder', 38, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Liam McCarron', 'Midfielder', 45, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Daniel James', 'Midfielder', 20, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Stuart McKinstry', 'Midfielder', 39, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Nohan Kenneh', 'Midfielder', 54, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Lewis Bate', 'Midfielder', 26, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Jack Jenkins', 'Midfielder', 47, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Patrick Bamford', 'Forward', 9, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Tyler Roberts', 'Forward', 11, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Raphinha', 'Forward', 10, 5);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Rodrigo', 'Forward', 19, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Sam Greenwood', 'Forward', 42, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leeds United', 'Joe Gelhardt', 'Forward', 30, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Kasper Schmeichel', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Danny Ward', 'Goalkeeper', 12, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Eldin Jakupovic', 'Goalkeeper', 35, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Jakub Stolarczyk', 'Goalkeeper', 41, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'James Justin', 'Defender', 2, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Wesley Fofana', 'Defender', 3, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Çaglar Söyüncü', 'Defender', 4, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Jonny Evans', 'Defender', 6, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Daniel Amartey', 'Defender', 18, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Ricardo Pereira', 'Defender', 21, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Timothy Castagne', 'Defender', 27, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Luke Thomas', 'Defender', 33, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Filip Benkovic', 'Defender', 34, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Ryan Bertrand', 'Defender', 5, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Jannik Vestergaard', 'Defender', 23, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Vontae Daley-Campbell', 'Defender', 38, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Ben Nelson', 'Defender', 45, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Youri Tielemans', 'Midfielder', 8, 3);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'James Maddison', 'Midfielder', 10, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Marc Albrighton', 'Midfielder', 11, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Harvey Barnes', 'Midfielder', 7, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Hamza Choudhury', 'Midfielder', 20, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Nampalys Mendy', 'Midfielder', 24, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Wilfred Ndidi', 'Midfielder', 25, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Boubakary Soumaré', 'Midfielder', 42, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Kiernan Dewsbury-Hall', 'Midfielder', 22, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Thanawat Suengchitthawon', 'Midfielder', 48, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Wanya Marcal-Madivadua', 'Midfielder', 54, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Jamie Vardy', 'Forward', 9, 7);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Kelechi Iheanacho', 'Forward', 14, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Ayoze Pérez', 'Forward', 17, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Patson Daka', 'Forward', 29, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Leicester City', 'Ademola Lookman', 'Forward', 37, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Alisson', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Adrián', 'Goalkeeper', 13, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Caoimhin Kelleher', 'Goalkeeper', 62, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Loris Karius', 'Goalkeeper', 22, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Liam Hughes', 'Goalkeeper', 54, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Marcelo Pitaluga', 'Goalkeeper', 97, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Virgil van Dijk', 'Defender', 4, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Joseph Gomez', 'Defender', 12, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Konstantinos Tsimikas', 'Defender', 21, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Andrew Robertson', 'Defender', 26, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Joel Matip', 'Defender', 32, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Nathaniel Phillips', 'Defender', 47, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Trent Alexander-Arnold', 'Defender', 66, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Neco Williams', 'Defender', 76, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Ibrahima Konaté', 'Defender', 5, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Owen Beck', 'Defender', 63, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Fabinho', 'Midfielder', 3, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Thiago', 'Midfielder', 6, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'James Milner', 'Midfielder', 7, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Naby Keïta', 'Midfielder', 8, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Jordan Henderson', 'Midfielder', 14, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Alex Oxlade-Chamberlain', 'Midfielder', 15, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Curtis Jones', 'Midfielder', 17, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Harvey Elliott', 'Midfielder', 67, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'James Balagizi', 'Midfielder', 85, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Tyler Morton', 'Midfielder', 80, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Conor Bradley', 'Midfielder', 84, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Elijah Dixon-Bonner', 'Midfielder', 45, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Roberto Firmino', 'Forward', 9, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Sadio Mané', 'Forward', 10, 7);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Mohamed Salah', 'Forward', 11, 11);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Diogo Jota', 'Forward', 20, 7);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Divock Origi', 'Forward', 27, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Takumi Minamino', 'Forward', 18, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Kaide Gordon', 'Forward', 49, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Liverpool', 'Harvey Blair', 'Forward', 86, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Zack Steffen', 'Goalkeeper', 13, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Ederson', 'Goalkeeper', 31, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Scott Carson', 'Goalkeeper', 33, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Cieran Slicker', 'Goalkeeper', 84, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Kyle Walker', 'Defender', 2, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Rúben Dias', 'Defender', 3, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'John Stones', 'Defender', 5, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Nathan Aké', 'Defender', 6, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Oleksandr Zinchenko', 'Defender', 11, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Aymeric Laporte', 'Defender', 14, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Benjamin Mendy', 'Defender', 22, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'João Cancelo', 'Defender', 27, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Luke Mbete', 'Defender', 79, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Joshua Wilson-Esbrand', 'Defender', 97, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'CJ Egan-Riley', 'Defender', 56, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Finley Burns', 'Defender', 94, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Ilkay Gündogan', 'Midfielder', 8, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Rodri', 'Midfielder', 16, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Kevin De Bruyne', 'Midfielder', 17, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Bernardo Silva', 'Midfielder', 20, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Fernandinho', 'Midfielder', 25, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Phil Foden', 'Midfielder', 47, 3);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Jack Grealish', 'Midfielder', 10, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Cole Palmer', 'Midfielder', 80, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Romeo Lavia', 'Midfielder', 90, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'James McAtee', 'Midfielder', 87, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Raheem Sterling', 'Forward', 7, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Gabriel Jesus', 'Forward', 9, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Ferran Torres', 'Forward', 21, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Riyad Mahrez', 'Forward', 26, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester City', 'Samuel Edozie', 'Forward', 53, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'David de Gea', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Dean Henderson', 'Goalkeeper', 26, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Tom Heaton', 'Goalkeeper', 22, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Lee Grant', 'Goalkeeper', 13, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Matej Kovar', 'Goalkeeper', 51, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Victor Lindelöf', 'Defender', 2, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Eric Bailly', 'Defender', 3, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Phil Jones', 'Defender', 4, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Harry Maguire', 'Defender', 5, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Luke Shaw', 'Defender', 23, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Alex Telles', 'Defender', 27, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Aaron Wan-Bissaka', 'Defender', 29, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Diogo Dalot', 'Defender', 20, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Teden Mengi', 'Defender', 43, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Raphaël Varane', 'Defender', 19, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Paul Pogba', 'Midfielder', 6, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Fred', 'Midfielder', 17, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Bruno Fernandes', 'Midfielder', 18, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Nemanja Matic', 'Midfielder', 31, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Donny van de Beek', 'Midfielder', 34, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Scott McTominay', 'Midfielder', 39, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Hannibal Mejbri', 'Midfielder', 46, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Jesse Lingard', 'Midfielder', 14, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Juan Mata', 'Midfielder', 8, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Facundo Pellistri', 'Midfielder', 28, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Edinson Cavani', 'Forward', 21, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Anthony Martial', 'Forward', 9, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Marcus Rashford', 'Forward', 10, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Mason Greenwood', 'Forward', 11, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Amad Diallo', 'Forward', 16, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Anthony Elanga', 'Forward', 36, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Shola Shoretire', 'Forward', 47, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Jadon Sancho', 'Forward', 25, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Manchester United', 'Cristiano Ronaldo', 'Forward', 7, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Martin Dúbravka', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Karl Darlow', 'Goalkeeper', 26, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Mark Gillespie', 'Goalkeeper', 29, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Daniel Langley', 'Goalkeeper', 33, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Freddie Woodman', 'Goalkeeper', 27, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Ciaran Clark', 'Defender', 2, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Paul Dummett', 'Defender', 3, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Fabian Schär', 'Defender', 5, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Jamaal Lascelles', 'Defender', 6, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Jamal Lewis', 'Defender', 12, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Emil Krafth', 'Defender', 17, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Federico Fernández', 'Defender', 18, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Javier Manquillo', 'Defender', 19, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Jonjo Shelvey', 'Midfielder', 8, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Matt Ritchie', 'Midfielder', 11, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Isaac Hayden', 'Midfielder', 14, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Jeff Hendrick', 'Midfielder', 16, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Ryan Fraser', 'Midfielder', 21, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Jacob Murphy', 'Midfielder', 23, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Miguel Almirón', 'Midfielder', 24, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Sean Longstaff', 'Midfielder', 36, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Elliot Anderson', 'Midfielder', 32, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Joseph Willock', 'Midfielder', 28, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Joe White', 'Midfielder', 56, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Joelinton', 'Forward', 7, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Allan Saint-Maximin', 'Forward', 10, 3);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Dwight Gayle', 'Forward', 34, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Newcastle United', 'Callum Wilson', 'Forward', 9, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Tim Krul', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Michael McGovern', 'Goalkeeper', 33, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Angus Gunn', 'Goalkeeper', 28, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Max Aarons', 'Defender', 2, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Sam Byram', 'Defender', 3, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Grant Hanley', 'Defender', 5, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Christoph Zimmermann', 'Defender', 6, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Bali Mumba', 'Defender', 26, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Andrew Omobamidele', 'Defender', 44, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Ben Gibson', 'Defender', 4, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Dimitris Giannoulis', 'Defender', 30, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Brandon Williams', 'Defender', 21, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Ozan Kabak', 'Defender', 15, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Lukas Rupp', 'Midfielder', 7, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Kieran Dowell', 'Midfielder', 10, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Przemyslaw Placheta', 'Midfielder', 11, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Todd Cantwell', 'Midfielder', 14, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Jacob Sørensen', 'Midfielder', 19, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Kenny McLean', 'Midfielder', 23, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Milot Rashica', 'Midfielder', 17, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Billy Gilmour', 'Midfielder', 8, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Pierre Lees-Melou', 'Midfielder', 20, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Mathias Normann', 'Midfielder', 16, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Teemu Pukki', 'Forward', 22, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Adam Idah', 'Forward', 35, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Joshua Sargent', 'Forward', 24, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Norwich City', 'Christos Tzolis', 'Forward', 18, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Alex McCarthy', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Harry Lewis', 'Goalkeeper', 41, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Fraser Forster', 'Goalkeeper', 44, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Kyle Walker-Peters', 'Defender', 2, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Jack Stephens', 'Defender', 5, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Mohammed Salisu', 'Defender', 22, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Jan Bednarek', 'Defender', 35, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Yan Valery', 'Defender', 43, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Romain Perraud', 'Defender', 15, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Valentino Livramento', 'Defender', 21, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Thierry Small', 'Defender', 16, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Lyanco', 'Defender', 4, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Oriol Romeu', 'Midfielder', 6, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'James Ward-Prowse', 'Midfielder', 8, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Nathan Redmond', 'Midfielder', 11, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Moussa Djenepo', 'Midfielder', 19, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Stuart Armstrong', 'Midfielder', 17, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'William Smallbone', 'Midfielder', 8, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Nathan Tella', 'Midfielder', 23, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Ibrahima Diallo', 'Midfielder', 27, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Mohamed Elyounoussi', 'Midfielder', 24, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Che Adams', 'Forward', 10, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Shane Long', 'Forward', 7, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Theo Walcott', 'Forward', 32, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Armando Broja', 'Forward', 18, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Southampton', 'Adam Armstrong', 'Forward', 9, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Hugo Lloris', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Pierluigi Gollini', 'Goalkeeper', 22, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Brandon Austin', 'Goalkeeper', 40, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Matt Doherty', 'Defender', 2, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Sergio Reguilón', 'Defender', 3, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Davinson Sánchez', 'Defender', 6, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Joe Rodon', 'Defender', 14, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Japhet Tanganga', 'Defender', 25, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Ben Davies', 'Defender', 33, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Eric Dier', 'Defender', 15, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Cristian Romero', 'Defender', 4, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Maksim Paskotsi', 'Defender', 48, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Kallum Cesay', 'Defender', 50, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Brooklyn Lyons-Foster', 'Defender', 53, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Emerson Royal', 'Defender', 12, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Tobi Omole', 'Defender', 49, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Malachi Fagan-Walcott', 'Defender', 46, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Pierre-Emile Højbjerg', 'Midfielder', 5, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Harry Winks', 'Midfielder', 8, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Giovani Lo Celso', 'Midfielder', 18, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Dele Alli', 'Midfielder', 20, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Tanguy Ndombele', 'Midfielder', 28, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Ryan Sessegnon', 'Midfielder', 19, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Oliver Skipp', 'Midfielder', 29, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Harvey White', 'Midfielder', 42, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Nile John', 'Midfielder', 43, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Matthew Craig', 'Midfielder', 51, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Romaine Mundle', 'Midfielder', 55, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Michael Craig', 'Midfielder', 52, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Son Heung-Min', 'Forward', 7, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Harry Kane', 'Forward', 10, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Steven Bergwijn', 'Forward', 23, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Lucas Moura', 'Forward', 27, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Jack Clarke', 'Forward', 47, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Bryan Gil', 'Forward', 11, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Dane Scarlett', 'Forward', 44, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Tottenham Hotspur', 'Dilan Markanday', 'Forward', 54, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Ben Foster', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Daniel Bachmann', 'Goalkeeper', 26, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Robert Elliot', 'Goalkeeper', 35, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Jeremy Ngakia', 'Defender', 2, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'William Troost-Ekong', 'Defender', 5, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Adam Masina', 'Defender', 11, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Craig Cathcart', 'Defender', 15, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Kiko Femenía', 'Defender', 21, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Christian Kabasele', 'Defender', 27, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Francisco Sierralta', 'Defender', 31, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Danny Rose', 'Defender', 3, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'James Morris', 'Defender', 42, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Nicolas Nkoulou', 'Defender', 13, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Tom Cleverley', 'Midfielder', 8, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Ken Sema', 'Midfielder', 12, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Dan Gosling', 'Midfielder', 16, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Daniel Phillips', 'Midfielder', 52, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Imran Louza', 'Midfielder', 6, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Ignacio Pussetto', 'Midfielder', 33, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Peter Etebo', 'Midfielder', 4, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Kwadwo Baah', 'Midfielder', 34, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Juraj Kucka', 'Midfielder', 33, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Ozan Tufan', 'Midfielder', 18, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Moussa Sissoko', 'Midfielder', 19, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'João Pedro', 'Forward', 10, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Ismaila Sarr', 'Forward', 23, 5);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Emmanuel Dennis', 'Forward', 25, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Ashley Fletcher', 'Forward', 17, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Joshua King', 'Forward', 7, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Watford', 'Cucho Hernández', 'Forward', 29, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Lukasz Fabianski', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'David Martin', 'Goalkeeper', 25, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Darren Randolph', 'Goalkeeper', 35, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Alphonse Areola', 'Goalkeeper', 13, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Aaron Cresswell', 'Defender', 3, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Vladimir Coufal', 'Defender', 5, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Angelo Ogbonna', 'Defender', 21, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Issa Diop', 'Defender', 23, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Ryan Fredericks', 'Defender', 24, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Arthur Masuaku', 'Defender', 26, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Craig Dawson', 'Defender', 15, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Winston Reid', 'Defender', 2, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Jamal Baptiste', 'Defender', 75, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Kurt Zouma', 'Defender', 4, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Ajibola Alese', 'Defender', 42, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Ben Johnson', 'Defender', 31, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Harrison Ashby', 'Defender', 50, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Manuel Lanzini', 'Midfielder', 10, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Mark Noble', 'Midfielder', 16, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Pablo Fornals', 'Midfielder', 8, 4);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Tomas Soucek', 'Midfielder', 28, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Declan Rice', 'Midfielder', 41, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Nikola Vlasic', 'Midfielder', 11, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Alex Král', 'Midfielder', 33, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Daniel Chesters', 'Midfielder', 51, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Andriy Yarmolenko', 'Forward', 7, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Saïd Benrahma', 'Forward', 22, 3);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Jarrod Bowen', 'Forward', 20, 2);
INSERT INTO Players(team, name, position, number, goals) VALUES ('West Ham United', 'Michail Antonio', 'Forward', 9, 6);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'John Ruddy', 'Goalkeeper', 21, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'José Sá', 'Goalkeeper', 1, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Louie Moulden', 'Goalkeeper', 13, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'James Storer', 'Goalkeeper', 48, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Ki-Jana Hoever', 'Defender', 2, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Marçal', 'Defender', 5, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Willy Boly', 'Defender', 15, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Conor Coady', 'Defender', 16, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Jonny', 'Defender', 19, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Nélson Semedo', 'Defender', 22, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Maximilian Kilman', 'Defender', 23, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Yerson Mosquera', 'Defender', 14, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Rayan Aït-Nouri', 'Defender', 3, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Rúben Neves', 'Midfielder', 8, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Daniel Podence', 'Midfielder', 10, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Romain Saïss', 'Midfielder', 27, 1);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'João Moutinho', 'Midfielder', 28, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Leander Dendoncker', 'Midfielder', 32, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Luke Cundle', 'Midfielder', 39, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Pedro Neto', 'Forward', 7, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Raúl Jiménez', 'Forward', 9, 3);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Fábio Silva', 'Forward', 17, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Adama Traoré', 'Forward', 37, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Trincão', 'Forward', 11, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Chem Campbell', 'Forward', 77, 0);
INSERT INTO Players(team, name, position, number, goals) VALUES ('Wolverhampton Wanderers', 'Hwang Hee-Chan', 'Forward', 26, 4);
