INSERT INTO Managers(name, nationality, team) VALUES ('Mikel Arteta', 'Spain', 'Arsenal');
INSERT INTO Managers(name, nationality, team) VALUES ('Thomas Frank', 'Denmark', 'Brentford');
INSERT INTO Managers(name, nationality, team) VALUES ('Graham Potter', 'England', 'Brighton and Hove Albion');
INSERT INTO Managers(name, nationality, team) VALUES ('Sean Dyche', 'England', 'Burnley');
INSERT INTO Managers(name, nationality, team) VALUES ('Thomas Tuchel', 'Germany', 'Chelsea');
INSERT INTO Managers(name, nationality, team) VALUES ('Patrick Vieira', 'France', 'Crystal Palace');
INSERT INTO Managers(name, nationality, team) VALUES ('Rafael Benitez', 'Spain', 'Everton');
INSERT INTO Managers(name, nationality, team) VALUES ('Marcelo Bielsa', 'Argentina', 'Leeds United');
INSERT INTO Managers(name, nationality, team) VALUES ('Brendan Rodgers', 'Northern Ireland', 'Leicester City');
INSERT INTO Managers(name, nationality, team) VALUES ('Jürgen Klopp', 'Germany', 'Liverpool');
INSERT INTO Managers(name, nationality, team) VALUES ('Josep Guardiola', 'Spain', 'Manchester City');
INSERT INTO Managers(name, nationality, team) VALUES ('Ole Gunner Solsajker', 'Norway', 'Manchester United');
INSERT INTO Managers(name, nationality, team) VALUES ('Graeme Joenes', 'England', 'Newcastle United');
INSERT INTO Managers(name, nationality, team) VALUES ('Dean Smith', 'England', 'Norwich City');
INSERT INTO Managers(name, nationality, team) VALUES ('Ralph Hasenhütti', 'Austria', 'Southampton');
INSERT INTO Managers(name, nationality, team) VALUES ('Antonio Conte', 'Italy', 'Tottenham Hotspur');
INSERT INTO Managers(name, nationality, team) VALUES ('Claudio Ranieri', 'Italy', 'Watford');
INSERT INTO Managers(name, nationality, team) VALUES ('David Moyes', 'Scotland', 'West Ham United');
INSERT INTO Managers(name, nationality, team) VALUES ('Bruno Lage', 'Portugal', 'Wolverhampton Wanderers');
INSERT INTO Managers(name, nationality, team) VALUES ('Steven Gerrard', 'England', 'Aston Villa');